Traduzione sezione "Genti del Reame"
claudiofreda/Dungeon-World-Italiano pull request #3
Opened 2024-01-01 13:50 UTC by stickgrinder

@claudiofreda spero che questa PR non sia esageratamente grossa. È una delle sezioni mancanti tra i capitoli dei mostri.

Ho cercato di mantenere il tono originale e spero di aver usato correttamente il glossario.
Nei prossimi giorni procedo con l'ultima sezione mancante.

2024-01-01 13:51 UTC, stickgrinder commented
@claudiofreda scusa, per errore questa PR contiene anche il commit della #2.
Magari porta dentro prima quella.
Grazie

2024-01-20 12:27 UTC, claudiofreda commented
Sto facendo commenti su tutto. Prima di concludere la PR, ho bisogno che riordini tutto in ordine alfabetico.

Fallo come ultima cosa, in un commit separato, in maniera da facilitarmi la revisione.

2024-01-20 13:30 UTC, claudiofreda requested changes

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +“Non possono essere tutti Sommi Sacerdoti, dicevano. Non tutti possono brandire la Lancia Bianca, dicevano. Pulisci il pavimento, mi hanno ordinato. Al Dio Supermo Cthonic non piacciono certo i pavim
"non si può essere tutti il Sommo Sacerdote"

Prova a metterci il Papa e ti rendi conto che la traduzione idiomatica è questa.

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +“Non possono essere tutti Sommi Sacerdoti, dicevano. Non tutti possono brandire la Lancia Bianca, dicevano. Pulisci il pavimento, mi hanno ordinato. Al Dio Supermo Cthonic non piacciono certo i pavim
"ordinavano", non hai usato il passato prossimo nelle altre.

"Dio Supremo" non "Supermo"

"Cthonic" è un aggettivo, con il suffisso -onic di origine latina, in Italiano è -onico, quindi va tradotto come "Cthonico", Come "Platonic" -> "Platonico"

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +“Non possono essere tutti Sommi Sacerdoti, dicevano. Non tutti possono brandire la Lancia Bianca, dicevano. Pulisci il pavimento, mi hanno ordinato. Al Dio Supermo Cthonic non piacciono certo i pavim
suggerisco "Mi avevano promesso saggezza e magia". Illuminazione è tecnicamente corretto ma non disambigua abbastanza tra "illumination" e "enlightenment".

Altra cosa: l'uso di queste frasi spezzettate è un tipico stilema degli autori, ma in italiano non funziona così bene. Io sarei leggermente più aggressivo sulle perifrasi e anche sulla punteggiatura.

"Bah, invece ho ottenuto soltanto ginocchia sbucciate e mani raggrinzite dal sapone."
"Se solo avessi scelto di fare il chierico."

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +- Offrire ricompensa eterna per le azioni mondane
o usi "ricompense eterne" o "una ricompensa eterna". Altrimenti l'italiano non ammette l'assenza di articolo al singolare in questo caso.

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +"Feccia della peggior specie, ecco cosa sono. Un gruppo di uomini e donne corazzati che arrivano nel paese come niente fosse, brandendo ciò che, ad ogni buon conto, è abbastanza potere magico e profa
"arrivano in paese"

Perché "profano"? "mondano" va benissimo qui, no?

Molto bene il resto, specialmente la traduzione di murderhobo. Anche "vagabondi assassini" andava bene, ma mi piace come l'hai messo.

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +Disperazione è la parola d'ordine del banditismo. In tempi duri, cos'altro rimane se non metter mano alle armi e unirsi a un clan di uomini e donne malvagi? Rapine sulle strade maestre, bracconaggio,
"La disperazione", attento a non calcare l'uso degli articoli in inglese.

"nasty" è più "cattivo" o "odioso" che "malvagio". Lo metterei prima di "uomini e donne", semplicemente perché si applica ad entrambi e mentalmente mi scorre meglio avere l'aggettivo prima, forse anche per enfasi.

ottimo "efferati"

Highway robbery sarebbe il banditismo o brigantaggio.

Manca l'ultima frase "Anyways---it's this or starve".

Il resto ottimo

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +- Chiedere tributo
Esigere un tributo

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +## Re dei Banditi
non usiamo le maiuscole così nei titoli in italiano. (lo so non è consistente con il resto del sito ma devo sistemarlo)

"Re dei banditi"

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +Alla corte del Re c'è solo una persona autorizzata a dire la verità. La pura, schietta e onesta verità su qualsiasi cosa. Il buffone potrà nasconderla tra campanellini, capriole e cerone sul viso, ma
"autorizzato" è molto moderno. Direi "a cui è permesso"

ottimo "cerone"

"what's what" direi "come stanno le cose" non "cosa succede veramente"

Non vedo perché l'aggiunta del punto dopo "si suol dire", la virgola sta benissimo. L'italiano generalmente tende a un periodare più lungo dell'inglese, quindi quando accorci i periodi non mi suona giusto.

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +- Denunciare l'ingiustizia
le ingiustizie

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +*Istinto*: Eseguire gli ordini
Ottimo

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +Nobile protettore o semplice ubriacone, spesso a loro fa poca differenza. Sebbene non siano nobili cavalieri, le guardie cittadine possono andar fiere della loro antica professione. Questi rappresent
"quando si vedono sotto lo sporco" (l'italiano è più lasso con l'uso di "vedere", non c'è bisogno di calcare l'uso inglese)

"armi decenti e armature calzanti a pennello"

Attento agli usi di singolare con articolo indeterminativo contro il plurale, l'uso idiomatico è diverso in italiano e inglese.

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +Nobile protettore o semplice ubriacone, spesso a loro fa poca differenza. Sebbene non siano nobili cavalieri, le guardie cittadine possono andar fiere della loro antica professione. Questi rappresent
"Quando i cavalieri neri sono avvistati nei boschi"

Sul trattino:
1. Il trattino che hai usato è un hyphen, non si usa in quel modo, l'inglese usa un em dash o en dash.

2. L'uso dei trattini come punteggiatura non esiste in italiano, perciò devi cambiarlo, solitamente in un punto, una parentesi, o un duepunti (in questo caso il più appropriato è il due punti)

"uno di loro insulta tua madre da ubriaco"

Il resto bene

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +## Ladro Mezzuomo
non continuo a ripetere la cosa delle maiuscole nei titoli, fallo per tutto, a meno che la seconda parola non meriti una sua maiuscola per un'altra ragione

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +Ora, sarebbe sciocco trarre conclusioni sulle persone solo perché hanno talento in una cosa o nell'altra. D'altro canto, pane al pane e vino al vino, no? O forse tra i mezzuomini, solo quelli dal cuo
Mi piace la traduzione del proverbio.

"Non tutti prendono quel titolo così sul ridere", se togli la parola "titolo" non si capisce a cosa ti riferisci

"chiede" non "chied" ma in generale "che chiede l'elemosina" mi sembra superfluo

Ancora uso dell'hyphen, anche questo non lo ripeto, correggilo dappertutto: niente hyphen o dash in italiano, in questo caso metterei una virgola al suo posto.

Il resto ottimo

Il resto molto bene

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +- Metti l'apparenza dell'amicizia
Sempre infinito, mai imperativo su queste mosse da mostro

"Ostentare la parvenza dell'amicizia" direi

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +## Mago di campagna
Direi più "mago errante" o addirittura "fattucchiere" che è la traduzione usata da D&D

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +Non tutti coloro che esercitano le arti arcane sono maghi avventurieri. Né negromanti nei mausolei o stregoni di antica stirpe. Alcuni sono semplicemente uomini e donne anziani, abbastanza svegli da
L'uso di "nor" a inizio periodo in inglese proprio non funziona in italiano.

Io direi "Non tutti [...] avventurieri, negromanti da mausoleo o stregoni di antica stirpe."

"Alcuni sono vecchietti o vecchiette"

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +Non tutti coloro che esercitano le arti arcane sono maghi avventurieri. Né negromanti nei mausolei o stregoni di antica stirpe. Alcuni sono semplicemente uomini e donne anziani, abbastanza svegli da
Sì si scrive con l'accento se è l'esclamazione. Ma lo trovo superfluo qui, la frase funziona anche senza.

"ma se devi spezzare una maledizione o provare il tuo amore"

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +- Concludere affari fuori portata
"Fare accordi fuori dalla propria portata"

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +Rispettati da tutti coloro che li guardano, i Sommi Sacerdoti e le Badesse di Dungeon World sono trattati con grande reverenza. Sia che rendano omaggio a Ur-thuu-hak, Dio delle Spade, o sussurrino pr
"facciamo strada"

Davvero ottimo il resto

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +Le terre selvagge ospitano molto più che semplici bestie con corna e scaglie. Ci sono anche uomini e donne là fuori, quelli che annusano il sangue nel vento e pattugliano le pianure indossando le pel
Ottimo, niente da dire

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +Quale giovane non si aggrappa alla ringhiera durante la possente giostra, accecato dai riflessi del sole sulle loro armature scintillanti, desiderando di poter esser lui a vestirsi d'acciaio e cavalc
"peasant" direi "villico" non "contadino"

Il resto ottimo.

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +“Dieci piedi di pali. Prendi i tuoi pali da dieci piedi, qui. Torce, luminose e calde. Anche i muli: testardi ma immacolati. Ti serve una confezione di biancheria, vero? Proprio qui! Vieni a prendere
"Pertiche da tre metri" è un riferimento alla tipica lunghezza delle pertiche nelle vecchie edizioni di D&D, con 10 piedi che sono circa 3 metri.

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +“Dieci piedi di pali. Prendi i tuoi pali da dieci piedi, qui. Torce, luminose e calde. Anche i muli: testardi ma immacolati. Ti serve una confezione di biancheria, vero? Proprio qui! Vieni a prendere
Dato che lo sta urlando alla folla dovrebbe essere tutto all'imperativo plurale.

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +“Dieci piedi di pali. Prendi i tuoi pali da dieci piedi, qui. Torce, luminose e calde. Anche i muli: testardi ma immacolati. Ti serve una confezione di biancheria, vero? Proprio qui! Vieni a prendere
"allevati irreprensibilmente" non "immacolati"

"Linen sack" non è una confezione di biancheria, è un sacco di lino. Linen indica il materiale del sacco, non il contenuto.

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +Che siano al loro posto per potere divino? È per questo che riescono a trasmettere ricchezza e potere per diritto di nascita? Qualche trucco o incantesimo nel sangue, magari? Il contadino piega il gi
"che siano dove sono"
"volere divino"
"È" non "E"
direi "possono" non "riescono", riescono sembra che facciano uno sforzo
"le ricchezze e il potere"
"forse." non c'è la domanda nell'originale
"bend the knee" è "inginocchiarsi" non "piegare il ginocchio"
"scrapes" è "tira a campare" non ha niente a che vedere con il grattare il suolo
"peasant" è "villico" non "contadino" lo dico perché l'accezione è alla classe sociale e non al lavoro, e a mio parere "contadino" è un termine usato anche modernamente per riferirsi a un lavoro.

cambierei la punteggiatura e farei una breve perifrasi alla fine "[...] posto, e dicono che tutti portiamo dei fardelli.
ricorda che in inglese "our" il possessivo è praticamente gratis perché include l'articolo determinativo. In italiano questo uso è molto più raro perché il possessivo appesantisce la frase.

Confronta "Andiamo alla macchina" "Let's go to my/your/our car". Non diresti mai "Andiamo alla tua macchina" a meno che non ci fosse da distinguere tra la tua macchina e quella di qualcun altro, ma in questo contesto probabilmente sappiamo benissimo di chi è la macchina. Quindi il possessivo in italiano si esprime solo per disambiguare, mentre in inglese si usa molto più spesso.

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +## Contadino
Solita cosa su "villico" invece di "contadino"

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +Coperti di fango, calpestati in fondo alla grande catena dell'esistenza, siamo tutti sulle spalle di coloro che coltivano il nostro cibo nelle fattorie. Alcuni contadini se la cavano meglio di altri,
"calpestati e in fondo" altrimenti non mi suona questa costruzione perché "in fondo" sembra un complemento di "calpestati" invece è una cosa a parte.

"coltivano il cibo" stessa cosa di prima sui possessivi

"non comportarti come se non fossi stato uno di loro prima di aver perso quel poco di buon senso che avevi"

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +*Istinto*: Cavarsela
Sopravvivere

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +*Istinto*: Cavarsela
O ancor meglio "tirare avanti"

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +Nelle campagne sarebbero chiamati fuorilegge, scacciati o uccisi. La città però, è piena di posti in cui nascondersi. Seminterrati umidi dove memorizzare mappe, pianificare e complottare contro un si
"fuorilegge e scacciati o uccisi"
"La città però" senza virgola dopo, e aggiungerei il duepunti dopo "nascondersi"

"rosicchiano pian piano l'ordine"
"per soppiantarlo con uno nuovo"
"o soltanto eroderlo completamente"

Il resto bene

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +## Soldati
Soldato al singolare

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +Per un bifolco con le braccia muscolose, a volte la scelta è tra fare il soldato o fare il bandito. È portare i colori, indossare armature della taglia sbaglata e marciare verso l'ignoto con un migli
"dal braccio forte"
"È" non "E" ma in ogni caso direi "Si tratta di"
"un'armatura".
"potrebbero piuttosto nascondersi nei boschi"
"nascondendosi dalle guardie"


Il resto bene

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +## Inventore
Ottimo

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +Amata dai re ma sempre guardata con sospetto. Misteriosa, riservata e affascinante, la vita di una spia è, agli occhi di un comune cittadino, piena di romanticismo e intrighi. È un coltello nel buio
Bene

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +- Riportare la verità
Fare rapporto della verità

2024-01-20 13:30 UTC, claudiofreda commented on mostri-genti.md
> +Si dice che se vedi un inventore per strada e non gli offri un sorso di birra o qualcosa da mangiare, ti lancerà appresso una maledizione di sfortuna. Gli inventori sono gente strana. Questi curiosi
"carri di cianfrusaglie", "colmi" è superfluo
metterei virgola tra "muli" e "con"
"A volte portano anche delle missive"
"O forse sono solo scorbutici rigattieri"

2024-02-07 03:53 UTC, stickgrinder commented on mostri-genti.md
> +- Offrire ricompensa eterna per le azioni mondane
Sei sicuro ne in nessun caso questo sia ammesso?

Prendi la frase: "Vivi nella rettutudine o l'aldilà sarà solo dolore e stridore di denti."
O più nel contesto: "Offro eterna gratitudine a chi mi porta un bicchier d'acqua."

In ogni caso correggo come indicato perchè la mia versione non mi piaceva e preferisco comunque la tua, ma sappimi dire se l'intenzione era grammaticalmente scorretta.

2024-02-07 03:59 UTC, stickgrinder commented on mostri-genti.md
> +"Feccia della peggior specie, ecco cosa sono. Un gruppo di uomini e donne corazzati che arrivano nel paese come niente fosse, brandendo ciò che, ad ogni buon conto, è abbastanza potere magico e profa
Semplice questione di come suona. Profano è generalmente contrapposto a "sacro", ma mi risulta sinonimo di "mondano". 

"Mondano", ancorché corretto, è un termine con due accezioni piuttosto differenti (essendo il secondo più tipo "edonista", "vivaiolo", etc)

Cosa ne pensi di "terreno"? Ti mando su questa modifica, se non ti piace fammi sapere e la cambio in "mondano".

2024-02-07 04:07 UTC, stickgrinder commented on mostri-genti.md
> +Disperazione è la parola d'ordine del banditismo. In tempi duri, cos'altro rimane se non metter mano alle armi e unirsi a un clan di uomini e donne malvagi? Rapine sulle strade maestre, bracconaggio,
Per "Disperazione": Non intendevo escludere gli articoli, ma suonare più canonico in Italiano. Probabilmente devo mettere delle virgolette? `"Disperazione" è la parola d'ordine del banditismo.`? Oppure meglio ancora (ma più distante dall'originale): `"Disperazione": ecco la parola d'ordine del banditismo.`. Provo con la prima, sappimi dire.

Ottimo per tutto il resto, corretto. Scusa ma l'ultima frase me la devo essere mangiata per errore.
Mando su la mia proposta.

2024-02-07 04:14 UTC, stickgrinder commented on mostri-genti.md
> +Disperazione è la parola d'ordine del banditismo. In tempi duri, cos'altro rimane se non metter mano alle armi e unirsi a un clan di uomini e donne malvagi? Rapine sulle strade maestre, bracconaggio,
Sto ripensando alla questione dell'aggettivo prima di "uomini e donne" e non mi suona troppo. Guarda:

* "non resta che unirsi a un clan di odiosi uomini e donne."
* "non resta che unirsi a un clan di uomini e donne odiosi."

Io trovo che l'aggettivo in fondo, rimanendo al maschile (neutro) dopo "donne", disambigui il fatto che si applica a entrambi. Al contrario mettendolo prima, non è così chiaro perchè mantiene il maschile e nella mia testa crea una sorta di raggruppamento.

Riguardo la traduzione di "nasty", più che odioso (che non mi pare in contesto) o cattivo (che è un po' infantile), userei "malevolo", oppure "sudicio", che mi è venuto in mente poter essere il significato originale... in quel caso "sudici uomini e donne" casca meglio.

In sintesi, cosa useresti tra:

1. "sudici uomini e donne"
1. "uomini e donne malevoli"

?

2024-02-07 04:22 UTC, stickgrinder commented on mostri-genti.md
> +- Chiedere tributo
Ma proprio si! 
Come ho fatto a scrivere quella zozzeria? :D

2024-02-07 04:24 UTC, stickgrinder commented on mostri-genti.md
> +Per un bifolco con le braccia muscolose, a volte la scelta è tra fare il soldato o fare il bandito. È portare i colori, indossare armature della taglia sbaglata e marciare verso l'ignoto con un migli
Proposta: cosa ne pensi di "dalle spalle larghe", al posto di "dal braccio forte"? Credo sia una traduzione più idiomatica che letterale.

Bene per tutto il resto, correggo.

2024-02-07 04:29 UTC, stickgrinder commented on mostri-genti.md
> +- Riportare la verità
"Fare rapporto" è ottimo si, molto meglio.

Che ne dici "Fare accuratamente rapporto"?
"Fare rapporto della verità" è corretto ma suona un po' letterale...

2024-02-07 04:32 UTC, stickgrinder commented on mostri-genti.md
> +Si dice che se vedi un inventore per strada e non gli offri un sorso di birra o qualcosa da mangiare, ti lancerà appresso una maledizione di sfortuna. Gli inventori sono gente strana. Questi curiosi
"Colmi" non mi dispiaceva come ritmo, ma l'ho rimosso. 
Perfetta la chiusura, la mia versione era penosa :) Grazie

2024-02-07 04:37 UTC, stickgrinder commented on mostri-genti.md
> +Per un bifolco con le braccia muscolose, a volte la scelta è tra fare il soldato o fare il bandito. È portare i colori, indossare armature della taglia sbaglata e marciare verso l'ignoto con un migli
Ho mandato su "dal fisico vigoroso". È più fluido a mio avviso, e non ci sono ambiguità con le "spalle larghe" metaforiche.

2024-02-07 04:43 UTC, stickgrinder commented
> Sto facendo commenti su tutto. Prima di concludere la PR, ho bisogno che riordini tutto in ordine alfabetico.
> 
> Fallo come ultima cosa, in un commit separato, in maniera da facilitarmi la revisione.

Riguardo all'ordine alfabetico, per "Re dei banditi", come mi devo comportare?

1. Lo lascio dopo banditi
2. Lo sposto in fondo
3. Lo lascio dove sta e lo titolo "Banditi (Re dei)" (o simili alternative)

Per ora lo sposto alfabeticamente, fammi sapere.
Grazie

2024-02-07 04:47 UTC, stickgrinder commented
@claudiofreda un altro commento. Nella mail che mi è arrivata quando hai aperto la review c'erano molti altri commenti (es. "Mago errante" al posto di "mago di campagna") o indicazioni sui tempi verbali, che qui non vedo.

Li hai chiusi o sono io che mi sto perdendo un pezzo?

2024-02-07 04:52 UTC, stickgrinder commented on mostri-genti.md
> +Alla corte del Re c'è solo una persona autorizzata a dire la verità. La pura, schietta e onesta verità su qualsiasi cosa. Il buffone potrà nasconderla tra campanellini, capriole e cerone sul viso, ma
Ottimo, per la questione punti e virgole, solo questione di stile e ritmo. A scuola ho avuto insegnanti che mi hanno fatto una testa così sull'uso di periodi corti per non rendere illeggibile la prosa.

Comunque l'ho cambiato, va benissimo.

2024-02-07 04:56 UTC, stickgrinder commented on mostri-genti.md
> +Nobile protettore o semplice ubriacone, spesso a loro fa poca differenza. Sebbene non siano nobili cavalieri, le guardie cittadine possono andar fiere della loro antica professione. Questi rappresent
> "uno di loro insulta tua madre da ubriaco"

Questa francamente la preferisco con l'inciso. Se ritieni sua illeggibile, la cambio.

2024-02-07 04:59 UTC, stickgrinder commented on mostri-genti.md
> +Nobile protettore o semplice ubriacone, spesso a loro fa poca differenza. Sebbene non siano nobili cavalieri, le guardie cittadine possono andar fiere della loro antica professione. Questi rappresent
Riguardo al trattino per l'inciso, a me risulta che l'italiano lo contempli, anche se è poco usato.
Ho controllato e qui c'è un riferimento: https://www.treccani.it/enciclopedia/trattino_(Enciclopedia-dell%27Italiano)/

Benissimo comunque per i due punti, che ho già corretto.

2024-02-07 05:06 UTC, stickgrinder commented on mostri-genti.md
> +- Metti l'apparenza dell'amicizia
Non avevo proprio capito cosa intendesse (per l'imperativo, errore mio!)

Che ne pensi di "Simulare amicizia"?

2024-02-07 05:10 UTC, stickgrinder commented on mostri-genti.md
> +- Concludere affari fuori portata
Propongo una variante che scorre meglio.

2024-02-07 05:14 UTC, stickgrinder commented on mostri-genti.md
> +“Dieci piedi di pali. Prendi i tuoi pali da dieci piedi, qui. Torce, luminose e calde. Anche i muli: testardi ma immacolati. Ti serve una confezione di biancheria, vero? Proprio qui! Vieni a prendere
L'ho reso meno letterale ma secondo me funziona.

2024-02-07 05:20 UTC, stickgrinder commented on mostri-genti.md
> +Che siano al loro posto per potere divino? È per questo che riescono a trasmettere ricchezza e potere per diritto di nascita? Qualche trucco o incantesimo nel sangue, magari? Il contadino piega il gi
> bend the knee

Mi preme sottolineare che in qualità di grande fan dei Manowar, questo mi era ben noto :smile: 
Ho tenuto "piegare il ginoccio" perchè mi sembrava solenne. Lo cambio.

Sulla questione "villico/contadino", userò villico dappertutto, sebbene non veda questa grande problematica. La classe sociale e il mestiere tendevano ad essere decisamente congruenti nel periodo a cui si ispira questo tipo di fantasy :wink:

2024-02-07 05:26 UTC, stickgrinder commented on mostri-genti.md
> +## Soldati
Typo, ho sbagliato a prendere il tasto.

2024-03-17 22:36 UTC, stickgrinder commented
@claudiofreda news su questa PR? Come sono andato con le correzioni?

2024-03-18 20:22 UTC, claudiofreda commented
Ciao! Scusami, mi sono dimenticato di guardare. Entro qualche giorno ti do feedback.

On Mon, Mar 18, 2024 at 00:37, Paolo Pustorino ***@***.***(mailto:On Mon, Mar 18, 2024 at 00:37, Paolo Pustorino <<a href=)> wrote:

> ***@***.***(https://github.com/claudiofreda) news su questa PR? Come sono andato con le correzioni?
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/claudiofreda/Dungeon-World-Italiano/pull/3#issuecomment-2002641111), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AAQTDYR5JC762XCLK4KTUOLYYYLJNAVCNFSM6AAAAABBJBOCMSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMBSGY2DCMJRGE).
> You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-05-06 14:07 UTC, claudiofreda commented
Ciao, scusami tanto. Mi sono perso. Adesso cerco di recuperare.

On Monday, 18 March 2024 at 22:22, Claudio Freda ***@***.***> wrote:

> Ciao! Scusami, mi sono dimenticato di guardare. Entro qualche giorno ti do feedback.
>
> On Mon, Mar 18, 2024 at 00:37, Paolo Pustorino ***@***.***(mailto:On Mon, Mar 18, 2024 at 00:37, Paolo Pustorino <<a href=)> wrote:
>
>> ***@***.***(https://github.com/claudiofreda) news su questa PR? Come sono andato con le correzioni?
>>
>> —
>> Reply to this email directly, [view it on GitHub](https://github.com/claudiofreda/Dungeon-World-Italiano/pull/3#issuecomment-2002641111), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AAQTDYR5JC762XCLK4KTUOLYYYLJNAVCNFSM6AAAAABBJBOCMSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMBSGY2DCMJRGE).
>> You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-05-07 07:49 UTC, stickgrinder commented
Ciao. Non ti preoccupare, ho immaginato e stavo aspettando.

In ogni caso anche io ho dato priorità a contribuzioni di altro genere. Se però questa entra, prometto di terminare le due sezioni mancanti entro quest'estate. Almeno mentre rilavori il tutto il sito sarà accessibile in Italiano a tutti i giocatori che ne hanno bisogno :)

Grazie

2024-05-07 11:00 UTC, merged

2024-05-07 11:08 UTC, claudiofreda commented
Ho integrato la pull request. Grazie del contributo e scusa il ritardo nella revisione.

On Tuesday, 7 May 2024 at 10:50, Paolo Pustorino ***@***.***> wrote:

> Ciao. Non ti preoccupare, ho immaginato e stavo aspettando.
>
> In ogni caso anche io ho dato priorità a contribuzioni di altro genere. Se però questa entra, prometto di terminare le due sezioni mancanti entro quest'estate. Almeno mentre rilavori il tutto il sito sarà accessibile in Italiano a tutti i giocatori che ne hanno bisogno :)
>
> Grazie
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/claudiofreda/Dungeon-World-Italiano/pull/3#issuecomment-2097668710), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AAQTDYQSCLJWDKKIJTI7K7LZBCBTVAVCNFSM6AAAAABBJBOCMSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAOJXGY3DQNZRGA).
> You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-05-07 11:26 UTC, stickgrinder commented
Grazie mille! È stato un piacere e ti ringrazio per la review completa e approfondita!
Spero di non farti dispetto se lavoro anche il resto :)

A presto

2024-05-07 11:32 UTC, claudiofreda commented
No, fai pure.

On Tue, May 7, 2024 at 14:26, Paolo Pustorino ***@***.***(mailto:On Tue, May 7, 2024 at 14:26, Paolo Pustorino <<a href=)> wrote:

> Grazie mille! È stato un piacere e ti ringrazio per la review completa e approfondita!
> Spero di non farti dispetto se lavoro anche il resto :)
>
> A presto
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/claudiofreda/Dungeon-World-Italiano/pull/3#issuecomment-2098180856), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AAQTDYQBSCTILGX62ZS2GQLZBC26VAVCNFSM6AAAAABBJBOCMSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAOJYGE4DAOBVGY).
> You are receiving this because you modified the open/close state.Message ID: ***@***.***>